# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_link.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddLink(QtCore.QObject):
    update_demands = QtCore.pyqtSignal(str)

    def add_link(self):
        node1 = self.n1
        node2 = self.graph.get_node_based_on_label(self.target_txt.text())
        can_i_add = True
        if node2 is None:
            QtWidgets.QMessageBox.critical(
                    self.horizontalLayoutWidget, "Error!", "Target Node not in Graph !"
                )
            can_i_add = False
        try:
            local_ip = self.local_ip_txt.text()
            remote_ip = self.remote_ip_txt.text()
            metric = int(self.metric_txt.text())
            capacity = int(self.capacity_txt.text())
        except ValueError:
            QtWidgets.QMessageBox.critical(
                    self.horizontalLayoutWidget, "Error!", "The metric/capacity must be an integer!"
                )
            can_i_add = False

        if can_i_add:
            self.graph.add_vertex(n1=node1, n2=node2, metric=metric,util=0,local_ip=local_ip,remote_ip=remote_ip,capacity=capacity)
            self.graph.add_vertex(n1=node2, n2=node1, metric=metric,util=0,local_ip=remote_ip,remote_ip=local_ip,capacity=capacity)
            self.graph.update_linknum(node1,node2)
            self.graph.update_linknum(node2,node1)
            self.update_demands.emit('oh well run the reports if you must')


    def setupUi(self, AddLink,n1,graph):
        self.n1 = n1
        self.graph = graph
        AddLink.setObjectName("AddLink")
        AddLink.setWindowModality(QtCore.Qt.WindowModal)
        AddLink.resize(430, 279)
        AddLink.setFocusPolicy(QtCore.Qt.ClickFocus)
        AddLink.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        AddLink.setWindowTitle("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(AddLink)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 30, 195, 23))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.source_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.source_layout.setContentsMargins(0, 0, 0, 0)
        self.source_layout.setObjectName("source_layout")
        self.source_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_lbl.sizePolicy().hasHeightForWidth())
        self.source_lbl.setSizePolicy(sizePolicy)
        self.source_lbl.setMinimumSize(QtCore.QSize(65, 0))
        self.source_lbl.setObjectName("source_lbl")
        self.source_layout.addWidget(self.source_lbl)
        self.source_txt = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.source_txt.setMinimumSize(QtCore.QSize(110, 0))
        self.source_txt.setMaximumSize(QtCore.QSize(110, 16777215))
        self.source_txt.setObjectName("source_txt")
        self.source_layout.addWidget(self.source_txt)
        self.add_btn = QtWidgets.QPushButton(AddLink)
        self.add_btn.setGeometry(QtCore.QRect(140, 210, 160, 32))
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(AddLink)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(120, 60, 195, 23))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.target_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.target_layout.setContentsMargins(0, 0, 0, 0)
        self.target_layout.setObjectName("target_layout")
        self.target_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.target_lbl.sizePolicy().hasHeightForWidth())
        self.target_lbl.setSizePolicy(sizePolicy)
        self.target_lbl.setMinimumSize(QtCore.QSize(65, 0))
        self.target_lbl.setObjectName("target_lbl")
        self.target_layout.addWidget(self.target_lbl)
        self.target_txt = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.target_txt.setMinimumSize(QtCore.QSize(110, 0))
        self.target_txt.setMaximumSize(QtCore.QSize(110, 16777215))
        self.target_txt.setObjectName("target_txt")
        self.target_layout.addWidget(self.target_txt)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(AddLink)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(120, 90, 195, 23))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.local_ip_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.local_ip_layout.setContentsMargins(0, 0, 0, 0)
        self.local_ip_layout.setObjectName("local_ip_layout")
        self.local_ip_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.local_ip_lbl.sizePolicy().hasHeightForWidth())
        self.local_ip_lbl.setSizePolicy(sizePolicy)
        self.local_ip_lbl.setMinimumSize(QtCore.QSize(65, 0))
        self.local_ip_lbl.setObjectName("local_ip_lbl")
        self.local_ip_layout.addWidget(self.local_ip_lbl)
        self.local_ip_txt = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.local_ip_txt.setMinimumSize(QtCore.QSize(110, 0))
        self.local_ip_txt.setMaximumSize(QtCore.QSize(110, 16777215))
        self.local_ip_txt.setObjectName("local_ip_txt")
        self.local_ip_layout.addWidget(self.local_ip_txt)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(AddLink)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(120, 120, 195, 23))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.remote_ip_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.remote_ip_layout.setContentsMargins(0, 0, 0, 0)
        self.remote_ip_layout.setObjectName("remote_ip_layout")
        self.remote_ip_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remote_ip_lbl.sizePolicy().hasHeightForWidth())
        self.remote_ip_lbl.setSizePolicy(sizePolicy)
        self.remote_ip_lbl.setMinimumSize(QtCore.QSize(65, 0))
        self.remote_ip_lbl.setObjectName("remote_ip_lbl")
        self.remote_ip_layout.addWidget(self.remote_ip_lbl)
        self.remote_ip_txt = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.remote_ip_txt.setMinimumSize(QtCore.QSize(110, 0))
        self.remote_ip_txt.setMaximumSize(QtCore.QSize(110, 16777215))
        self.remote_ip_txt.setObjectName("remote_ip_txt")
        self.remote_ip_layout.addWidget(self.remote_ip_txt)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(AddLink)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(120, 150, 195, 23))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.metric_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.metric_layout.setContentsMargins(0, 0, 0, 0)
        self.metric_layout.setObjectName("metric_layout")
        self.metric_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metric_lbl.sizePolicy().hasHeightForWidth())
        self.metric_lbl.setSizePolicy(sizePolicy)
        self.metric_lbl.setMinimumSize(QtCore.QSize(65, 0))
        self.metric_lbl.setObjectName("metric_lbl")
        self.metric_layout.addWidget(self.metric_lbl)
        self.metric_txt = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.metric_txt.setMinimumSize(QtCore.QSize(110, 0))
        self.metric_txt.setMaximumSize(QtCore.QSize(110, 16777215))
        self.metric_txt.setObjectName("metric_txt")
        self.metric_layout.addWidget(self.metric_txt)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(AddLink)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(120, 180, 195, 23))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.capacity_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.capacity_layout.setContentsMargins(0, 0, 0, 0)
        self.capacity_layout.setObjectName("capacity_layout")
        self.capacity_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capacity_lbl.sizePolicy().hasHeightForWidth())
        self.capacity_lbl.setSizePolicy(sizePolicy)
        self.capacity_lbl.setMinimumSize(QtCore.QSize(65, 0))
        self.capacity_lbl.setObjectName("capacity_lbl")
        self.capacity_layout.addWidget(self.capacity_lbl)
        self.capacity_txt = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.capacity_txt.setMinimumSize(QtCore.QSize(110, 0))
        self.capacity_txt.setMaximumSize(QtCore.QSize(110, 16777215))
        self.capacity_txt.setObjectName("capacity_txt")
        self.capacity_layout.addWidget(self.capacity_txt)

        #connect btn
        self.add_btn.clicked.connect(self.add_link)

        self.retranslateUi(AddLink)
        QtCore.QMetaObject.connectSlotsByName(AddLink)

    def retranslateUi(self, AddLink):
        _translate = QtCore.QCoreApplication.translate
        self.source_lbl.setText(_translate("AddLink", "Source"))
        self.source_txt.setText(_translate("AddLink", str(self.n1.label) ))
        self.add_btn.setText(_translate("AddLink", "Add"))
        self.target_lbl.setText(_translate("AddLink", "Target"))
        self.target_txt.setText(_translate("AddLink", "Target Node"))
        self.local_ip_lbl.setText(_translate("AddLink", "Local IP"))
        self.local_ip_txt.setText(_translate("AddLink", "172.16.0.1"))
        self.remote_ip_lbl.setText(_translate("AddLink", "Remote IP"))
        self.remote_ip_txt.setText(_translate("AddLink", "172.16.0.2"))
        self.metric_lbl.setText(_translate("AddLink", "Metric"))
        self.metric_txt.setText(_translate("AddLink", "10"))
        self.capacity_lbl.setText(_translate("AddLink", "Capacity"))
        self.capacity_txt.setText(_translate("AddLink", "1000"))

